
# Root SonarCloud Configuration

sonar.projectKey=SafwanIrfan_10pearls-contact-management-system
sonar.projectName=10pearls-contact-management-system
sonar.organization=safwanirfan


# Module Definitions
sonar.modules=frontend,backend


# Frontend Module (React)
frontend.sonar.projectName=frontend
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.language=js
frontend.sonar.exclusions=**/*.test.js,**/*.spec.js,**/*.test.jsx,**/*.spec.jsx,**/node_modules/**,**/build/**,**/coverage/**
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Backend Module (Spring Boot - Maven)
backend.sonar.projectName=backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.language=java
backend.sonar.java.binaries=target/classes
backend.sonar.java.test.binaries=target/test-classes
backend.sonar.exclusions=**/target/**