name: CI + SonarCloud + Coverage

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Frontend
        working-directory: frontend
        run: npm install

      - name: Give execute permission to mvnw
        working-directory: backend
        run: chmod +x mvnw

      # Backend tests + JaCoCo
      - name: Backend Tests
        working-directory: backend
        run: ./mvnw test

      # SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
